config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    resources :home
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: "users/registrations"
      }


    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end



    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"


      resources :categories
      resources :articles
      resources :galleries
      resources :users
      resources :admins
    end

    get 'users' => 'users#index', :as => "users"
    post 'users' => "users#create"
    get 'signup' => "users#new", :as => "new_user"
    get "users/:id/edit" => "users#edit", :as => "edit_user"
    get "users/:id" => "users#show", :as => "user"
    patch "users/:id" => "users#update"
    put "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"


end

app/models/gallery.rb
class Gallery < ApplicationRecord
    belongs_to :admin, optional: true

    has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :admin_only?

  def index
    @gallery = current_admin.galleries.build
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new

  end

  def create
    @gallery = current_admin.galleries.build(galleries_params)
    if @gallery.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_galleries_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or category Duplicated"
        format.html { redirect_to admin_galleries_path }
        format.js { render template: "admin/galleries/gallery_error.js.erb" }
      end
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update(galleries_params)
      redirect_to admin_gallery_path(@gallery), notice: "Successful Updated"
    else
      render :edit
    end
  end

  def destroy
    @gallery = Gallery.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_galleries_url }
      format.js
    end
  end

  private
    def admin_only?
      unless  current_admin.admin?
        unless @user == current_admin
          redirect_to admin_dashboard_path, notice: "Access Denied"
        end
      end
    end

    def galleries_params
      params.required(:gallery).permit!
    end
end

app/helpers/admin/galleries_helper.rb
module Admin::GalleriesHelper
end

app/views/admin/galleries/_gallery.html.erb
<tr class="delete_gallery_<%=gallery.id%>">

  <td>
    <%= gallery.id%>
  </td>

  <td>
    <%=status_converter(gallery.status)%>
  </td>

  <td>
    <%=time_ago(gallery.created_at)%>
  </td>

  <td>
    <%=form_for([:admin, gallery], remote: true) do |f|%>
      <%=link_to admin_gallery_path(gallery), email: "View" do %>
        View
      <%end%>
      <%=link_to edit_admin_gallery_path(gallery), email: "Edit",id: "show-form_#{gallery.id}" do %>
        Edit
      <%end%>
    <%end%>
  </td>
  <td style="display: none;">ass</td>
</tr>

app/views/admin/galleries/_gallery_form.html.erb
<%=simple_form_for([:admin, gallery], remote: true) do |f|%>
  <div class="row">

    <div class="col-md-12" style="margin-bottom: 20px;">
      <h3>Upload Photo</h3>
        <div class="controls">
            <%=f.file_field :image%>
        </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <label class="control-label mb-10 text-left">Your product is now <%=status_converter(@gallery.status)%></label>
        <div class="checkbox checkbox-success">
          <%=f.check_box :status, id: "checkbox3"%>
          <label for="checkbox3">
            Status
          </label>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%=f.submit class: "btn btn-success"%>
      </div>
    </div>
  </div>

<%end%>

app/views/admin/galleries/create.js.erb
$("input#gallery_gallery_name").val("");
$("#gallery-errors").html(" ");
$("#gallery-success").html("<%= custom_flash_message%>");
$("#gallery-index").append("<%=escape_javascript render(@gallery)%>");

$(function() {
  $('.delete_gallery_<%=@gallery.id%>').submitOnCheck();
});

$('.delete_gallery_<%=@gallery.id%>').submitOnCheck();

app/views/admin/galleries/destroy.js.erb
$('.delete_gallery_<%=@gallery.id%>').remove();

app/views/admin/galleries/edit.html.erb
	<div class="page-wrapper">
		<div class="container pt-30">
			<div class="row">
				<div class="col-md-9">
					<div class="panel panel-success card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-light">Edit Gallery</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<%=simple_form_for([:admin, @gallery]) do |f|%>
									<div class="row">

								    <div class="col-md-12" style="margin-bottom: 20px;">
											<div class="form-group">
									        <div class="controls">
									            <%=f.file_field :image%>
									        </div>
									     </div>
										</div>
								   </div>

									<div class="col-md-12">
							      <div class="form-group">
							        <label class="control-label mb-10 text-left">Your product is now <%=status_converter(@gallery.status)%></label>
							        <div class="checkbox checkbox-success">
							          <%=f.check_box :status, id: "checkbox3"%>
							          <label for="checkbox3">
							            Status
							          </label>
							        </div>
							      </div>
							    </div>
									<div class="col-md-12">
										<div class="modal-footer">
											<%=link_to "Cancle", admin_galleries_path, class: "btn btn-default"%>
											<%=f.submit class: "btn btn-success"%>
										</div>
									</div>
								</div>

							<%end%>

						</div>
					</div>
				</div>
				<div class="col-md-3">
					<img src="<%=@gallery.image%>" alt="" width="200" height="200">
				</div>
			</div>
		</div>
	</div>

	<%=render "applications/footer"%>

</div>

app/views/admin/galleries/gallery_error.js.erb
$("input#gallery_gallery").val("");
$("#gallery-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/galleries/gallery_success.js.erb
$("input#gallery_gallery_name").val("");
$("#gallery-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/galleries/index.html.erb
<!-- Main Content -->
	<div class="page-wrapper">
		<div class="container pt-30">
			<!-- Title -->
			<div class="row heading-bg">
				<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
					<div class="panel-wrapper collapse in">
						<div class="panel-body" style="padding-left: 0px;">
							<div class="button-list">
								<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Add New</button>
							</div>
							<div class="modal fade bs-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
								<div class="modal-dialog modal-lg" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span></button>
											<h5 class="modal-title" id="exampleModalLabel1">New gallery</h5>
										</div>
										<div class="modal-body">
											<div id="galleries">
												<div id="gallery-errors"></div>
												<div id="gallery-success"></div>
												<%=render partial: "gallery_form", locals: {gallery: @gallery}%>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Breadcrumb -->
				<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
					<ol class="breadcrumb">
						<li>
							<a href="/admin/dashboard">Dashboard</a>
						</li>
						<li class="active">
							<span>gallery</span></li>
					</ol>
				</div>
				<!-- /Breadcrumb -->
			</div>
			<!-- /Title -->

			<!-- Row -->
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default border-panel card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-dark">gallery</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<div class="table-wrap">
									<div class="">
										<table id="myTable1" class="table table-hover display  pb-30">
											<thead>
												<tr>
													<th>ID</th>
													<th>Status</th>
													<th>Created At</th>
													<th>Actions</th>
													<th style="display: none;">test</th>
												</tr>
											</thead>
											<tbody id="gallery-index">
												<%if @galleries.any?%>
													<%= render @galleries%>
												<%end%>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Row -->
		</div>

		<%=render "applications/footer"%>

	</div>

app/views/admin/galleries/show.html.erb
<div class="page-wrapper">
		<div class="container pt-30">
			<div class="row">
				<div class="col-md-6">
					<div class="panel panel-success card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-light">Gallery Detail</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<span>
									<span>
										<img src="<%=@gallery.image%>" style="margin-bottom: 20px;" height="300" class="img-responsive" alt="">
									</span>
								</span>

								<div class="pull-left">
									<%=link_to "Cancel", admin_galleries_path, class: "btn btn-warning"%>
									<%=link_to "Edit", edit_admin_gallery_path(@gallery), class: "btn btn-success"%>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<%=render "applications/footer"%>

	</div>