config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    resources :home
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: "users/registrations"
      }


    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end



    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"


      resources :categories
      resources :articles
      resources :galleries
      resources :users
      resources :admins
    end

    get 'users' => 'users#index', :as => "users"
    post 'users' => "users#create"
    get 'signup' => "users#new", :as => "new_user"
    get "users/:id/edit" => "users#edit", :as => "edit_user"
    get "users/:id" => "users#show", :as => "user"
    patch "users/:id" => "users#update"
    put "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"


end

app/models/article.rb
class Article < ApplicationRecord
    before_save :update_slug

    belongs_to :admin
    belongs_to :category

    def update_slug
        self.slug = title.parameterize
    end
    
    def to_param
        slug
    end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @article = current_admin.articles.build
    @articles = Article.all
  end

  def show
    @article = Article.find_by_slug(params[:id])
  end

  def new
    
  end

  def create
    @article = current_admin.articles.build(article_params)
    if @article.save
      respond_to do |format|
        flash.now[:notice] = "Created Successful"
        format.html { redirect_to admin_articles_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or article duplicated"
        format.html { redirect_to admin_articles_path}
        format.js
      end
    end
  end

  def edit
    @article = Article.find_by_slug(params[:id])
  end

  def update
    @article = Article.find_by_slug(params[:id])
    if @article.update(article_params)
      redirect_to admin_article_path(@article), notice: "Successful Updated"
    else
      render :edit
    end
  end

  def destroy
    @article = Article.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Deleted"
      format.html { redirect_to admin_articles_path }
      format.js
    end
  end

  private
    def admin_only
      unless current_admin.admin?
        unless @user == current_admin
          redirect_to admin_dashboard_path, notice: "Access denied"
        end
      end
    end

    def article_params
      params.required(:article).permit!
    end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_article.html.erb
<tr class="delete_article_<%=article.id%>">

  <td>
    <%= article.title%>
  </td>

  <td>
    <%=time_ago(article.created_at)%>
  </td>

  <td>
    <%=form_for([:admin, article], remote: true) do |f|%>
      <%=link_to admin_article_path(article), email: "View" do %>
        View
      <%end%>
      <%=link_to edit_admin_article_path(article), email: "Edit",id: "show-form_#{article.id}" do %>
        Edit
      <%end%>
    <%end%>
  </td>
</tr>

app/views/admin/articles/_article_form.html.erb
<%=simple_form_for([:admin, article], remote: true) do |f|%>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Article Name</label>
        <%=f.text_field :title, class: "form-control"%>
      </div>
    </div>
    <div class="col-md-12">
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%=f.submit class: "btn btn-success"%>
      </div>
    </div>
  </div>

<%end%>

app/views/admin/articles/article_error.js.erb
$("input#article_article_name").val("");
$("#article-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/articles/article_success.js.erb
$("input#article_article_name").val("");
$("#article-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/articles/create.js.erb
$("input#article_article_name").val("");
$("#article-errors").html(" ");
$("#article-success").html("<%= custom_flash_message%>");
$("#article-index").append("<%=escape_javascript render(@article)%>");

$(function() {
  $('.delete_article_<%=@article.id%>').submitOnCheck();
});

$('.delete_article_<%=@article.id%>').submitOnCheck();

app/views/admin/articles/destroy.js.erb
$('.delete_article_<%=@article.id%>').remove();

app/views/admin/articles/edit.html.erb
<div class="page-wrapper">
		<div class="container pt-30">
			<div class="row">
				<div class="col-md-9">
					<div class="panel panel-success card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-light">Edit article</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<%=simple_form_for([:admin, @article]) do |f|%>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="recipient-name" class="control-label mb-10">article Name</label>
											<%=f.text_field :article_name, class: "form-control"%>
										</div>
									</div>
									<div class="col-md-12">
										<div class="modal-footer">
											<%=link_to "Cancle", admin_article_path, class: "btn btn-default"%>
											<%=f.submit class: "btn btn-success"%>
										</div>
									</div>
								</div>

							<%end%>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<%=render "applications/footer"%>

</div>

app/views/admin/articles/index.html.erb
<div class="page-wrapper">
		<div class="container pt-30">
			<!-- Title -->
			<div class="row heading-bg">
				<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
					<div class="panel-wrapper collapse in">
						<div class="panel-body" style="padding-left: 0px;">
							<div class="button-list">
								<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Add New</button>
							</div>
							<div class="modal fade bs-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
								<div class="modal-dialog modal-lg" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span></button>
											<h5 class="modal-title" id="exampleModalLabel1">New message</h5>
										</div>
										<div class="modal-body">
											<div id="articles">
												<div id="article-errors"></div>
												<div id="article-success"></div>
												<%=render partial: "article_form", locals: {article: @article}%>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Breadcrumb -->
				<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
					<ol class="breadcrumb">
						<li>
							<a href="/admin/dashboard">Dashboard</a>
						</li>
						<li class="active">
							<span>article</span></li>
					</ol>
				</div>
				<!-- /Breadcrumb -->
			</div>
			<!-- /Title -->

			<!-- Row -->
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default border-panel card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-dark">article</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<div class="table-wrap">
									<div class="">
										<table id="myTable1" class="table table-hover display  pb-30">
											<thead>
												<tr>
													<th>article Name</th>
													<th>Created At</th>
													<th>Actions</th>
												</tr>
											</thead>
											<tbody id="article-index">
												<%if @articles.any?%>
													<%= render @articles%>
												<%end%>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Row -->
		</div>

		<%=render "applications/footer"%>

	</div>

app/views/admin/articles/show.html.erb
<!-- Main Content -->
<div class="page-wrapper">
    <div class="container pt-30">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-success card-view">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h6 class="panel-title txt-light">article Detail</h6>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <span>
                                article Name:
                                <span><%=@article.article_name%></span>
                            </span>
                            <hr>
                            <hr>
                            <div class="pull-left">
                                <%=link_to "Cancel", admin_articles_path, class: "btn btn-warning"%>
                                <%=link_to "Edit", edit_admin_article_path(@article), class: "btn btn-success"%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%=render "applications/footer"%>

</div>