config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    resources :home
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: "users/registrations"
      }


    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end



    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"


      resources :categories
      resources :articles
      resources :galleries
      resources :users
      resources :admins
    end

    get 'users' => 'users#index', :as => "users"
    post 'users' => "users#create"
    get 'signup' => "users#new", :as => "new_user"
    get "users/:id/edit" => "users#edit", :as => "edit_user"
    get "users/:id" => "users#show", :as => "user"
    patch "users/:id" => "users#update"
    put "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_writer :login

  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]

  has_many :categories
  has_many :articles
  has_many :galleries
  has_many :users

  # has_and_belongs_to_many :permissions

  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  def login
    @login || self.username || self.email
  end

  enum role: [:user, :vip, :admin]

  def set_default_role
    self.role ||= :user
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true

end

app/models/article.rb
class Article < ApplicationRecord
    before_save :update_slug

    belongs_to :admin
    belongs_to :category

    def update_slug
        self.slug = title.parameterize
    end
    
    def to_param
        slug
    end
end

app/models/category.rb
class Category < ApplicationRecord
  before_save :update_slug
  validates :category_name, uniqueness: true, presence: true, length: { maximum: 20 }

  belongs_to :admin
  has_many :articles
  validates :category_name, presence: true

  def update_slug
    self.slug = category_name.parameterize
  end

  def to_param
    slug
  end
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    belongs_to :admin, optional: true

    has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  after_initialize :set_default_role, :if => :new_record?

  attr_writer :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]

  # validates :username, presence: :true, uniqueness: { case_sensitive: false }

  # validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  belongs_to :admin, optional: true
  # phony_normalize :phone, default_country_code: 'KH'
  # validates :phone_numer, phony_plausible: true
  # validates :phone_number, uniqueness: true
  validates :phone_number, presence: true
  # validates :phone, numericality: true

  # def active_for_authentication?
  #   super and self.is_active?
  # end

  def login
    @login || self.phone_number || self.email
  end

  enum role: [:user, :seller, :customer]

  def set_default_role
    self.role ||= :user
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(phone_number) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:phone_number) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end

end

app/controllers/home_controller.rb
class HomeController < FrontEndApplication

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  layout "front_end_application"
  before_action :set_cart
  def verify
    @search = Product.ransack(params[:search])
    @products = @search.result.includes(:category, :sub_category, :product_type)
    @categories = Category.all
    @user = User.last
    # Use Authy to send the verification token
    token = Authy::API.verify(id: @user.authy_id, token: params[:token])

    if token.ok?
      # Mark the user as verified for get /user/:id
      @user.update(verified: true)
      # Show the user profile
      redirect_to sign_in_path
    else
      flash.now[:danger] = "Incorrect code, please try again"
      render :show_verify
    end
  end

  def resend
    @user = User.last
    Authy::API.request_sms(id: @user.authy_id)
    flash[:notice] = 'Verification code re-sent'
    redirect_to verify_path
  end

  private
    def send_message(message)
      @user = current_user
      twilio_number = ENV['TWILIO_NUMBER']
      account_sid = ENV['TWILIO_ACCOUNT_SID']
      @client = Twilio::REST::Client.new account_sid, ENV['TWILIO_AUTH_TOKEN']
    end
    def set_cart
      if session[:cart_id]
        cart = Cart.find_by(id: session[:cart_id])
        if cart.present?
          @current_cart = cart
          if current_user
            cart.update(user_id: current_user.id)
          end
        else
          session[:cart_id] = nil
        end
      end

      if session[:cart_id].nil?
        @current_cart = Cart.create(:user_id => nil)
        session[:cart_id] = @current_cart.id
      end
    end

    def set_wishlist
      if session[:wishlist_id]
        wishlist = Wishlist.find_by(id: session[:wishlist_id])
        if wishlist.present?
          @current_wishlist = wishlist
          if current_user
            wishlist.update(user_id: current_user.id)
          end
        else
          session[:wishlist_id] = nil
        end
      end

      if session[:wishlist_id].nil?
        @current_wishlist = Wishlist.create(:user_id => nil)
        session[:wishlist_id] = @current_wishlist.id
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(datetime)
    datetime.strftime('%H:%M') unless datetime.blank?
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cash_drawers_helper.rb
module CashDrawersHelper
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/fast_cash_helper.rb
module FastCashHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pos_helper.rb
module PosHelper

  def display_change_in_usd (order)
    number_to_currency ((order.total_cash_in_riel - order.total * Constant::exchange_rate) / Constant::exchange_rate).to_i, precision: 0
  end

  def display_change_in_riel (order)
    n = (order.total_cash_in_riel - order.total * Constant::exchange_rate) / Constant::exchange_rate
    remain = n.to_s.split('.')
    return ('0.' + remain[1]).to_f * Constant::exchange_rate
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/admin/admins/_admin.html.erb
<tr class="delete_admin_<%=admin.id%>">

  <td>
    <%= admin.email%>
  </td>
  
  <td>
    <%=time_ago(admin.created_at)%>
  </td>

  <td>
    <%=form_for([:admin, admin], remote: true) do |f|%>
      <%=link_to admin_admin_path(admin), email: "View" do %>
        View
      <%end%>
      <%=link_to edit_admin_admin_path(admin), email: "Edit",id: "show-form_#{admin.id}" do %>
        Edit
      <%end%>
    <%end%>
  </td>
</tr>

app/views/admin/admins/_admin_form.html.erb
<%=simple_form_for([:admin, @admin], remote: true) do |f|%>
  <div class="row">

    <div class="col-md-12">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Role</label>
        <%=f.select :role,(Admin.roles.keys.map{ |role| [role.titleize, role]}), {}, {:class=>"form-control"}%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">First Name</label>
        <%=f.text_field :first_name, class: "form-control"%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Last Name</label>
        <%=f.text_field :last_name, class: "form-control"%>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Username</label>
        <%=f.text_field :username, class: "form-control"%>
      </div>
    </div>


    <div class="col-md-12">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Email</label>
        <%=f.text_field :email, class: "form-control"%>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Password</label>
        <%=f.password_field :password, class: "form-control", placeholder: "Password"%>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Confirmation Password</label>
        <%=f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"%>
      </div>
    </div>

    <div class="col-md-12">
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%=f.submit class: "btn btn-success"%>
      </div>
    </div>

  </div>

<%end%>

app/views/admin/admins/admin_error.js.erb
$("input#admin_admin_name").val("");
$("#admin-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/admins/admin_success.js.erb
$("input#admin_admin_name").val("");
$("#admin-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/admins/create.js.erb
$("input#admin_admin_name").val("");
$("#admin-errors").html(" ");
$("#admin-success").html("<%= custom_flash_message%>");
$("#admin-index").append("<%=escape_javascript render(@admin)%>");

$(function() {
  $('.delete_admin_<%=@admin.id%>').submitOnCheck();
});

$('.delete_admin_<%=@admin.id%>').submitOnCheck();

app/views/admin/admins/destroy.js.erb
$('.delete_admin_<%=@admin.id%>').remove();

app/views/admin/admins/edit.html.erb
	<div class="page-wrapper">
		<div class="container pt-30">
			<div class="row">
				<div class="col-md-9">
					<div class="panel panel-success card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-light">Edit admin</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<%=simple_form_for([:admin, @admin]) do |f|%>
								<div class="row">
									<div class="col-md-12">
							      <div class="form-group">
							        <label for="recipient-name" class="control-label mb-10">Role</label>
							        <%=f.select :role,(Admin.roles.keys.map{ |role| [role.titleize, role]}), {}, {:class=>"form-control"}%>
							      </div>
							    </div>

							    <div class="col-md-6">
							      <div class="form-group">
							        <label for="recipient-name" class="control-label mb-10">First Name</label>
							        <%=f.text_field :first_name, class: "form-control"%>
							      </div>
							    </div>

							    <div class="col-md-6">
							      <div class="form-group">
							        <label for="recipient-name" class="control-label mb-10">Last Name</label>
							        <%=f.text_field :last_name, class: "form-control"%>
							      </div>
							    </div>

							    <div class="col-md-12">
							      <div class="form-group">
							        <label for="recipient-name" class="control-label mb-10">Username</label>
							        <%=f.text_field :username, class: "form-control"%>
							      </div>
							    </div>


							    <div class="col-md-12">
							      <div class="form-group">
							        <label for="recipient-name" class="control-label mb-10">Email</label>
							        <%=f.text_field :email, class: "form-control"%>
							      </div>
							    </div>

							    <div class="col-md-12">
							      <div class="form-group">
							        <label for="recipient-name" class="control-label mb-10">Password</label>
											<p>Leave it blank if you don't want to change your password</p>
							        <%=f.password_field :password, class: "form-control", placeholder: "Password"%>
							      </div>
							    </div>

							    <div class="col-md-12">
							      <div class="form-group">
							        <label for="recipient-name" class="control-label mb-10">Confirmation Password</label>
											<p>Leave it blank if you don't want to change your password</p>
											<%=f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"%>
							      </div>
							    </div>
									<div class="col-md-12">
										<div class="modal-footer">
											<%=link_to "Cancle", admin_admin_path, class: "btn btn-default"%>
											<%=f.submit class: "btn btn-success"%>
										</div>
									</div>
								</div>

							<%end%>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<%=render "applications/footer"%>

</div>

app/views/admin/admins/index.html.erb
	<div class="page-wrapper">
		<div class="container pt-30">
			<!-- Title -->
			<div class="row heading-bg">
				<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
					<div class="panel-wrapper collapse in">
						<div class="panel-body" style="padding-left: 0px;">
							<div class="button-list">
								<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Add New</button>
							</div>
							<div class="modal fade bs-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
								<div class="modal-dialog modal-lg" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span></button>
											<h5 class="modal-title" id="exampleModalLabel1">New message</h5>
										</div>
										<div class="modal-body">
											<div id="admins">
												<div id="admin-errors"></div>
												<div id="admin-success"></div>
												<%=render partial: "admin_form", locals: {admin: @admin}%>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Breadcrumb -->
				<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
					<ol class="breadcrumb">
						<li>
							<a href="/admin/dashboard">Dashboard</a>
						</li>
						<li class="active">
							<span>admin</span></li>
					</ol>
				</div>
				<!-- /Breadcrumb -->
			</div>
			<!-- /Title -->

			<!-- Row -->
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default border-panel card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-dark">admin</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<div class="table-wrap">
									<div class="">
										<table id="myTable1" class="table table-hover display  pb-30">
											<thead>
												<tr>
													<th>admin Name</th>
													<th>Created At</th>
													<th>Actions</th>
												</tr>
											</thead>
											<tbody id="admin-index">
												<%if @admins.any?%>
													<%= render @admins%>
												<%end%>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Row -->
		</div>

		<%=render "applications/footer"%>

	</div>

app/views/admin/admins/show.html.erb
	<!-- Main Content -->
	<div class="page-wrapper">
		<div class="container pt-30">
			<div class="row">
				<div class="col-md-6">
					<div class="panel panel-success card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-light">Admin Detail</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<span>
									admin Name:
									<span><%=@admin.username%></span>
								</span>
								<hr>
								<hr>
								<div class="pull-left">
									<%=link_to "Cancel", admin_admins_path, class: "btn btn-warning"%>
									<%=link_to "Edit", edit_admin_admin_path(@admin), class: "btn btn-success"%>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<%=render "applications/footer"%>

	</div>

app/views/shared/_cart.html.erb
<div id="out_of_stock_error" style="display: none;"></div>

<!-- Preloader -->
<div id="preloader" class="preloader">
  <div class="loader-cube">
    <div class="loader-cube__item1 loader-cube__item"></div>
    <div class="loader-cube__item2 loader-cube__item"></div>
    <div class="loader-cube__item4 loader-cube__item"></div>
    <div class="loader-cube__item3 loader-cube__item"></div>
  </div>
</div>
<!-- End Preloader -->
<!-- ––––––––––––––––––––––––––––––––––––––––– -->
<!-- WRAPPER -->
<!-- ––––––––––––––––––––––––––––––––––––––––– -->
<div id="pageWrapper" class="page-wrapper">
  <!-- –––––––––––––––[ HEADER ]––––––––––––––– -->
  <header id="mainHeader" class="main-header">

    <!-- Top Bar -->
    <%=render "front-end/topbar"%>
    <!-- End Top Bar -->

    <!-- Header Header -->
    <%=render "front-end/header"%>
    <!-- End Header Header -->

    <!-- Header Menu -->
    <%=render "front-end/header-menu"%>
    <!-- End Header Menu -->

  </header>
  <!-- –––––––––––––––[ HEADER ]––––––––––––––– -->

  <!-- –––––––––––––––[ PAGE CONTENT ]––––––––––––––– -->
  <main id="mainContent" class="main-content">
    <div class="page-container" style="margin-top: 35px;">
      <div class="container">
        <div class="cart-area ptb-60">
          <div class="container">
            <div class="cart-wrapper">
              <h3 class="h-title mb-30 t-uppercase">My Cart</h3>
              <div class="container">
                <div class="row">
                  <div class="col-sm-8">
                    <table id="cart_list" class="cart-list mb-30">
                      <thead class="panel t-uppercase">
                        <tr>
                          <th style="font-size: 10px;">Product name</th>
                          <th style="font-size: 10px;">Unit price</th>
                          <th style="font-size: 10px;">Quantity</th>
                          <th style="font-size: 10px;">Sub total</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        <%@cart.line_items.each do |line_item|%>
                          <tr class="panel alert reduce_qty_<%=line_item.id%>" id="delete_cart_<%=line_item.id%>">
                          <td>
                            <div class="media-left is-hidden-sm-down">
                              <figure class="product-thumb">
                                <%line_item.product.assets.limit(1).each do |asset|%>
                                  <img src="<%=asset.product%>" alt="product">
                                <%end%>
                              </figure>
                            </div>
                            <div class="media-body valign-middle">
                              <h6 class="title mb-15 t-uppercase">
                                <a href="#"><%=line_item.product.product_name.capitalize%></a>
                              </h6>
                              <div class="type font-12">
                                <span class="t-uppercase">Type :
                                </span><%=line_item.product.category.category_name%>
                              </div>
                            </div>
                          </td>
                          <td><%=number_to_currency(line_item.product.product_price)%></td>
                          <td>

                            <%=link_to line_item_reduce_path(:id => line_item) , method: :post , style: "margin-top:15px;",class: "reduce-qty",remote: true do %>
                              <i class="fa fa-minus"></i>
                            <% end %>

                            <span class="qty" id="qty_<%=line_item.id%>"><%=line_item.quantity%></span>
                            <%=link_to line_item_add_path(:id => line_item) , method: :post , style: "margin-top:15px;",class: "increase-qty",remote: true do %>
                              <i class="fa fa-plus"></i>
                            <% end %>
                          </td>
                          <td>
                            <div class="sub-total" id="sub-total_<%=line_item.id%>"><%=number_to_currency(line_item.total_price)%></div>
                          </td>
                          <td class="col-sm-1">
                            <%=link_to line_item_path(@current_cart.line_items.find_by(product_id: line_item.product.id)) ,method: :delete ,class: "close pr-xs-0 pr-sm-10", remote: true do %>
                              <i class="fa fa-trash-o"></i>
                              <% end %>
                          </td>
                        </tr>
                        <%end%>
                      </tbody>
                    </table>
                    <div class="t-left">
                      <%=link_to "Continue Shopping", products_path, class: "btn btn-rounded btn-lg"%>
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="review-wrapper clearfix">
                      <div class="cart-price">

                        <h5 class="t-uppercase mb-20">Cart total</h5>
                        <ul class="panel mb-20">
                          <li>
                            <div class="item-name">
                              Subtotal
                            </div>
                            <div class="price" id="sub_total">
                              <%=number_to_currency(@cart.sub_total)%>
                            </div>
                          </li>
                          <li>
                            <div class="item-name">
                              Delivery Fee
                            </div>
                            <div class="price">
                              $00.00
                            </div>
                          </li>
                          <li>
                            <div class="item-name">
                              <strong class="t-uppercase">Order total</strong>
                            </div>
                            <div class="price" id="sub_total_order">
                              <span><%=number_to_currency(@cart.sub_total)%></span>
                            </div>
                          </li>
                          <li>
                            <h6 class="t-uppercase mb-20" style="font-size: 12px;">
                              <b>Payment: Cash On Delivery</b>
                            </h6>
                          </li>
                        </ul>

                        <div class="t-right">

                            <%= button_to "Checkout", new_order_path , method: :get,class: "btn btn-rounded btn-lg"%>

                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <%=render "front-end/footer-area"%>

</div>

<div id="backTop" class="back-top is-hidden-sm-down">
  <i class="fa fa-angle-up" aria-hidden="true"></i>
</div>

<div id="minus_one" style="display: none;"></div>

app/views/shared/_cart_line_item.html.erb
<tr>
  <td>
  x
  <%= line_item.quantity %>
</td>
<td><%= product.product_name %></td>
<td>In stock</td>
<td class="text-center">
  <!-- reduce -->
  <%=link_to line_item_reduce_path(:id => line_item) , method: :post, class: "btn btn-danger" , style: "margin-top:15px;" do %>
    <i class="glyphicon glyphicon-minus" style="color:white;"></i>
  <% end %>
<!-- add -->
<%=link_to line_item_add_path(:id => line_item) , method: :post , class: "btn btn-success" , style: "margin-top:15px;" do %>
  <i class="glyphicon glyphicon-plus" style="color:white;"></i>
<% end %>
</td>
<td class="text-right"><%= product.product_price %>
$</td>
<td class="text-right">
<!-- Remove -->
<%=link_to line_item_path(line_item) ,method: :delete ,class: "btn btn-danger", data: { confirm: 'Are you sure?' } do %>
  <i class="fa fa-trash"></i>
<% end %>
</td>
</tr>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_order_product.html.erb
<li>


<strong>
  Name :
</strong>
<%= product.product_name %>

  Price :
</strong>
<%= product.product_price %> $

</li>

app/views/shared/_product.html.erb
<li>
<%= product.product_name %>

<%= product.product_price %>

</li>

app/views/shared/_products.html.erb
<ul class="users">
  <% if @products.present? %>
    <%= render @products %>
  <% end %>
</ul>